### ISSUE TITLE
Gemfile需要修改一下

### ISSUE THREAD

**Issue by jinleileiking** [saberma/shopqi#1]
gem 'mongoid', '2.0.0.beta.11'

多了个 .

**Comment by jinleileiking** [comment]
ler could not find compatible versions for gem "mongoid":
  In Gemfile:
    acts_as_list_mongoid depends on
      mongoid (>= 2.0.0.beta.15)

```
mongoid (2.0.0.beta.11)
```

**Comment by saberma** [comment]
ok，已经更新，今天就会上传

**Comment by saberma** [comment]
已经更新并上传了
