### ISSUE TITLE
用户可以查看dashboard

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#119]
用户登录后显示dashboard首页

首页上方显示订单和商品的一些统计信息
右边显示［最近订单］、［最近评论］

下方显示［最近动态］，包括商品、集合、博客等后台管理功能的新增修改功能的记录

**Comment by saberma** [comment]
统计时需要显示SKU，作为帐号等级的一部分(基础帐号Max SKUs＝100，专业帐号Max SKUs=2500)

**Comment by saberma** [comment]
处理订单活动记录时，要评估一下订单历史(OrderHistory)是否可以不要了，合并至活动记录

**Comment by liwh** [comment]
觉得订单历史还是有必要的
