### ISSUE TITLE
指引在ie下有问题。

### ISSUE THREAD

**Issue by liwh** [saberma/shopqi#130]
进入商品列表js报错:

消息: HTML Parsing Error: Unable to modify the parent container element before the child element is closed (KB927917)
行: 0
字符: 0
代码: 0
URI: http://shopqi.smackaho.st:4000/admin/products

**Comment by saberma** [comment]
同时修正顾客列表报错
done

**Comment by saberma** [comment]
此改动导致商品列表过滤条件“所有厂商”无法显示候选项
撤消改动后原问题也无法重现，暂时先撤消改动的代码

候选项显示样式不正确，等下处理

**Comment by saberma** [comment]
候选项样式不正确的问题已处理
