### ISSUE TITLE
完善商店前台模板集合变量

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#165]
通过collections.handle(如collections/frontpage)，要先查询custom_collection，再查询smart_collection，现只支持查询custom_collection

同时完善对应的单元测试，由于liquid变量无效时，后台并不抛出异常，我们很难在页面上进行(集成)测试，所以所有liquid的正确性都要通过单元测试来保证

**Comment by liwh** [comment]
默认包含types和vendors集合
集合在前台只显示公开状态的集合，其它的都转404页面
