### ISSUE TITLE
增加智能集合时报错

### ISSUE THREAD

**Issue by liwh** [saberma/shopqi#173]
NoMethodError in SmartCollectionsController#update

undefined method `variants_inventory_equals=' for #MetaSearch::Searches::Product:0x0000014f8da220

meta_search (1.1.0) lib/meta_search/builder.rb:135:in `method_missing'
meta_search (1.1.0) lib/meta_search/builder.rb:113:in`block in assign_attributes'
meta_search (1.1.0) lib/meta_search/builder.rb:112:in `each_pair'
meta_search (1.1.0) lib/meta_search/builder.rb:112:in`assign_attributes'
meta_search (1.1.0) lib/meta_search/builder.rb:87:in `build'
meta_search (1.1.0) lib/meta_search/searches/active_record.rb:43:in`metasearch'
activerecord (3.1.0) lib/active_record/relation.rb:455:in `block in method_missing'
activerecord (3.1.0) lib/active_record/relation.rb:180:in`block in scoping'
activerecord (3.1.0) lib/active_record/base.rb:1190:in `with_scope'
activerecord (3.1.0) lib/active_record/relation.rb:180:in`scoping'
activerecord (3.1.0) lib/active_record/relation.rb:455:in `method_missing'
activerecord (3.1.0) lib/active_record/associations/collection_proxy.rb:102:in`method_missing'
app/models/smart_collection.rb:40:in `rules_products'
app/models/smart_collection.rb:18:in`block in class:SmartCollection'
activesupport (3.1.0) lib/active_support/callbacks.rb:419:in `_run_save_callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:81:in`run_callbacks'
activerecord (3.1.0) lib/active_record/callbacks.rb:264:in `create_or_update'
activerecord (3.1.0) lib/active_record/persistence.rb:37:in`save'
activerecord (3.1.0) lib/active_record/validations.rb:50:in `save'
activerecord (3.1.0) lib/active_record/attribute_methods/dirty.rb:22:in`save'
activerecord (3.1.0) lib/active_record/transactions.rb:241:in `block (2 levels) in save'
activerecord (3.1.0) lib/active_record/transactions.rb:295:in`block in with_transaction_returning_status'
activerecord (3.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
activerecord (3.1.0) lib/active_record/transactions.rb:208:in`transaction'
activerecord (3.1.0) lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
activerecord (3.1.0) lib/active_record/transactions.rb:241:in`block in save'
activerecord (3.1.0) lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
activerecord (3.1.0) lib/active_record/transactions.rb:240:in`save'
app/controllers/smart_collections_controller.rb:26:in `update'
actionpack (3.1.0) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.1.0) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.1.0) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.1.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.1.0) lib/active_support/callbacks.rb:452:in`_run__2043997088273729793__process_action__2121839419887440846__callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:81:in`run_callbacks'

**Comment by saberma** [comment]
done
