### ISSUE TITLE
用户可以新增应用api授权

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#184]
在后台管理（/admin/api）中可以增加api授权，用于私有程序的访问

授权机制基于oauth2协议，服务端实现使用 https://github.com/songkick/oauth2-provider ，非gem，代码放在lib/oauth2中；之前实现主题授权时已经对现有的插件进行试用，这个使用是最方便的
客户端实现可先用浏览器测试，直接输入 api 的url地址(https://api_key:password@foo.myshopqi.com/admin/orders.json)

实现此功能时，要将api授权记录保持至applications表中，此表归属于shop记录；表字段有api_key,password,shared_secret，字段值都为32位随机字符；用户的私有程序可通过地址
https://483d797f39ddc77675924c2b62184680:5ec483f14ed790add61b43873323e75e@foo.myshopqi.com/admin/orders.xml
获取订单记录，其中 
483d797f39ddc77675924c2b62184680 为 api_key，
5ec483f14ed790add61b43873323e75e 为 password，shared_secret暂时用不到（在后面开发app时才需要使用，以生成url地址中的signature，及后台生成访问商店的password）

结合 #185 的issue， api请求过来时，控制器将通过请求参数 api_key, password 判断请求是否合法，具体参考
https://github.com/songkick/oauth2-provider
中的 Using password credentials 一节
也可参考 https://github.com/saberma/shopqi/blob/master/app/controllers/admin/shops_controller.rb#L25 ，其中的
authorization = OAuth2::Provider.access_token(nil, [], request) 就是要换为 Using password credentials 一节中所说的内容

刚开始会有不少疑惑的地方，随时联系

**Comment by liwh** [comment]
将api resource 独立到/api 这个namespace下面，  就是使用(https://api_key:password@foo.myshopqi.com/api/orders.json访问

**Comment by saberma** [comment]
使用独立的/api也好，还有问题你思考下，有没有必要(结合复杂度考虑)支持版本 /api/v1

**Comment by liwh** [comment]
不通过applications表保存,api_key等，application表用来保存商店所安装的应用。

通过api_clients表保存，用户商店生成的api_key password和共享密钥。

通过https://api_key:password@foo.myshopqi.com/api/orders.json 形式访问时，api_key password必须存在在商店 api_clients中，即有api_clients(包含对应的api_key ,password) 关联到商店。

**Comment by saberma** [comment]
好的，用api_clients更直观

**Comment by saberma** [comment]
提供api这个功能上可以分为两个阶段：
1. 由key:secret直接访问，这个阶段只需要验证key:secret有效就行了(不需要access_token)，就能用api获取资源，也就是说只要用active_resource测试能够正常调用api就行。应用场景一般为商店内部使用的系统，跟我们的商店可以做到快速集成
2. 由app通过oauth2访问，这个阶段app要通过access_token才能访问，应用场景为app提供给所有商店使用

虽然是两种方式访问api，但是我们的api程序也是用的同一套，只是before_filter认证时支持两种不同的应用场景
