### ISSUE TITLE
获取主题bug

### ISSUE THREAD

**Issue by liwh** [saberma/shopqi#193]
增加新主题失败,  利用url那种形式无法使用

**Comment by saberma** [comment]
这个问题之前我处理过了，跟你所做的修改 commit#4111895 类似
https://github.com/saberma/shopqi/commit/41118955fb5ebe2ceeb255af65573f5eb210657f
https://github.com/saberma/shopqi/blob/0.0.6-upload-theme/config/routes.rb#L106

主题功能我还在开发(改动较大)，如果有发现问题先把bug转给我
