### ISSUE TITLE
今天的版本有如下问题：

### ISSUE THREAD

**Issue by jinleileiking** [saberma/shopqi#2]
jinleileiking@jinleileiking-laptop:~/work/shopqi$ bundle install
Fetching source index for http://rubygems.org/
Updating git://github.com/saberma/mongoid_embedded_helper.git
fatal: ambiguous argument '7369220': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
An error has occurred in git when running `git reset --hard 7369220. Cannot complete bundling.

**Comment by saberma** [comment]
应该是因为我把mongoid_embedded_help repository删除后重建的原因。
已经修改GemFile，相应的lock也自动更新。
代码已经上传。

http://github.com/saberma/shopqi/commit/0b0c26fae60d7c093bcf295ba1c7ef74b5d0a703

**Comment by saberma** [comment]
测试报错了，我再查查

**Comment by saberma** [comment]
引入mongo adjust plugin，测试正常
