### ISSUE TITLE
ActiveRecord::StatementInvalid in Shop::CartController#update

### ISSUE THREAD

**Issue by liwh** [saberma/shopqi#248]
PGError: ERROR:  null value in column "session_id" violates not-null constraint
: INSERT INTO "carts" ("cart_hash", "created_at", "customer_id", "session_id", "shop_id", "token", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"

购物车结算时报错

![image](http://ww4.sinaimg.cn/large/6757a08cjw1dmy5ud4tuwj.jpg)

**Comment by liwh** [comment]
某些情况，如手动清楚了session,session id会为nil

```
03:52:08 web.1           | {
03:52:08 web.1           |              :key => "_shopqi_session",
03:52:08 web.1           |             :path => "/",
03:52:08 web.1           |           :domain => nil,
03:52:08 web.1           |     :expire_after => nil,
03:52:08 web.1           |           :secure => false,
03:52:08 web.1           |         :httponly => true,
03:52:08 web.1           |            :defer => false,
03:52:08 web.1           |            :renew => false,
03:52:08 web.1           |            :coder => #<Rack::Session::Cookie::Base64::Marshal:0x007ff0e011ea58>,
03:52:08 web.1           |               :id => nil
03:52:08 web.1           | }
```

所以，我觉得还是不要用session_id为好。。

**Comment by saberma** [comment]
http是无状态协议，而购物车是需要状态支持的，只有cookie能够弥补这个问题

之前是使用cookie来保存购物车(varaint_id|quantity;)，而后为了实现订单提交后清空购物车的功能
只能把原来放在cookie的字符串，改为使用redis存储(key为session_id)，订单一提交，删除redis存储，这样浏览器的购物车才会清空。

如果不使用session_id，也需要其他的保存在session中的东西代替，还不如直接使用id

在改为redis存储后，忽略了session的初始化，才会出现此问题
已经通过集成测试重现问题，并已经修正
