### ISSUE TITLE
sku数量超过商店限制后不能再新增商品和款式

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#282]

**Comment by liwh** [comment]
采用js $.get之类的去设置error,发现js作用域，无法设置error['aaa'] = 'aaa'到外部的error变量

**Comment by liwh** [comment]
不在js里面增加validate,直接使用render json,若没有返回值，则直接设定对应的错误提示

**Comment by liwh** [comment]
当sku超出使用限制时，也不能修改已有的款式

**Comment by liwh** [comment]
补充测试
