### ISSUE TITLE
商店后台管理帐号设置关闭商店功能没有实现删除商店

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#283]
只是删除了当前用户
要改为删除商店

关闭流程改为:
1. 点击关闭时在下方显示手机校验码输入框(后台发送校验码到手机，要限制发送频率，参考用户[重复]注册)
2. 用户输入校验码后，点击确认删除按钮；
3. 后台检查校验码正确后才destroy商店

**Comment by liwh** [comment]
修正流程为： 点击删除商店，跳到新的页面，然后，出一些对应的提示，比如说，删除商店的原因等等， 然后再是 跟着上面的流程

**Comment by saberma** [comment]
不要跳出新的页面，直接在当前页面操作按钮下方显示新的内容

**Comment by liwh** [comment]
是否考虑 不立即删除，而是 先将删除shop的请求，直接放到后台去， 然后，一个星期之内，如果用户没有任何操作（付款操作） 再直接删除？

**Comment by liwh** [comment]
短信验证码 限定发送在 商店拥有者的 手机号码 上

**Comment by saberma** [comment]
有反馈删除原因，还是跳出窗口合适一些；

同意非物理删除的方案，改为后台操作（考虑下resque scheduler），时间定为3个月后物理删除
官网后台管理加入商店[恢复]操作

有新窗口和非物理删除功能，短信功能可以不需要了
