### ISSUE TITLE
pivotaltracker.需要权限才能看

### ISSUE THREAD

**Issue by jinleileiking** [saberma/shopqi#3]
点这里查看哪些功能需要开发
“http://www.pivotaltracker.com/projects/84595”: http://www.pivotaltracker.com/projects/84595

**Comment by saberma** [comment]
之前开放了权限的，不知为何又失效了。T.T

现在已经重新公开了，我退出后都可以查看了，试试看。

**Comment by jinleileiking** [comment]
好了。
