### ISSUE TITLE
支付网关处，使用普通支付功能时提醒有问题。

### ISSUE THREAD

**Issue by weapon-zz** [saberma/shopqi#324]
在普通支付中选择邮局汇款后，点击保存，下面出现红色提示。但是看不清提示内容，再拉下一点，点保存时，提示保存成功。

**Comment by saberma** [comment]
重现步骤可能是在IE下增加了支付宝，同时下方多出来了"银行转帐"、"邮局汇款"，修改时就会出现错误

**Comment by saberma** [comment]
done
https://github.com/saberma/shopqi/commit/8879ad438ff96fb7af75f2c61e1c571b5a6edafc
