### ISSUE TITLE
在设置->email&提醒处，删除邮箱后，提示找不到页面。

### ISSUE THREAD

**Issue by weapon-zz** [saberma/shopqi#327]
步骤：1、刚开始进入的时候已经有了一个邮箱名称。2、点击新增邮件提醒，选择自己的姓名，之后有会新增一条与前面那条相同的邮箱地址。3、再新增一条新的邮箱地址（与前面的不一样的），之后删除第二条时，提示出错。

**Comment by saberma** [comment]
Chrome、IE7都没有办法重现问题
