### ISSUE TITLE
判断用户是否为管理，是则不校验权限

### ISSUE THREAD

**Issue by liwh** [saberma/shopqi#337]

**Comment by saberma** [comment]
要完善:
1. 有订单的情况下，订单菜单显示订单数后，会被显示为无权限
2. 商店新增时，用户为管理员，不增加permission记录

已经修正问题，正补集成测试

**Comment by saberma** [comment]
转移商店时清除新管理员的权限，并初始化旧管理员的权限

**Comment by saberma** [comment]
https://github.com/saberma/shopqi/commit/9f5685ec697b9d78af5272b4f8d954d7b22fc4bb
