### ISSUE TITLE
想通过shopqi项目去更多的了解ruby on Rails,但运行项目出问题! 求解 

### ISSUE THREAD

**Issue by huxinghai** [saberma/shopqi#410]
我运行 rails s命令

=> Ctrl-C to shutdown server
[DEPRECATION WARNING] Nested I18n namespace lookup under "activerecord.attributes.user" is no longer supported
[DEPRECATION WARNING] Nested I18n namespace lookup under "activerecord.attributes.product" is no longer supported
[2012-02-23 10:21:14] INFO  WEBrick 1.3.1
[2012-02-23 10:21:14] INFO  ruby 1.9.2 (2011-07-09) [x86_64-darwin11.0.0]
[2012-02-23 10:21:14] INFO  WEBrick::HTTPServer#start: pid=609 port=3000
有两个警告不知道会不会影响项目运行
当我在游览器输入http://localhost:3000/
No route matches [GET] "/"报路由错误,请仁兄帮助! 谢谢

**Comment by saberma** [comment]
你试下使用 www.lvh.me:3000 访问，ShopQi有判断域名的，不能直接使用localhost访问

不过建议你暂时不要看ShopQi的源代码了，不知道还能不能开源下去

**Comment by huxinghai** [comment]
谢谢...  OK 了
