### ISSUE TITLE
Missing setting 'port' in 'domain' section in /shopqi/config/app_config.yml

### ISSUE THREAD

**Issue by wyh770406** [saberma/shopqi#458]
Missing setting 'port' in 'domain' section in /shopqi/config/app_config.yml,
请教一下这个问题如何解决？

**Comment by wyh770406** [comment]
这个问题是我在rake db:migrate的时候碰到的

**Comment by saberma** [comment]
@wyh770406 谢谢反馈
已经修正问题了，你可以获取最新代码试下

**Comment by wyh770406** [comment]
可以了，谢谢，不过有另外一个问题，我在本地打开http://www.lvh.me:3000，然后注册http://www.lvh.me:3000/services/signup/new/free，可以选省，但是没有城市，和地区可选，请问一下这是什么原因？

**Comment by wyh770406** [comment]
找到原因了，是端口号的问题 把 app_config.yml 4000 改成 3000

**Comment by saberma** [comment]
@wyh770406 最好使用 4000 端口，因为 ShopQi 支持 App 注册，其他 App 可以使用 3000 端口，具体可以查看 [中文说明](https://github.com/saberma/shopqi#%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8Echinese-readme)

**Comment by wyh770406** [comment]
ok
