### ISSUE TITLE
注册用户时出现下面的错误

### ISSUE THREAD

**Issue by wyh770406** [saberma/shopqi#460]
A Errno::ENOENT occurred in registrations#create:

  No such file or directory - /home/wyh77/shopqi/data/themes/5/current/. 
  /usr/share/ruby-rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:1423:in `stat'

**Comment by wyh770406** [comment]
我创建一个商店的时候报错
A RuntimeError occurred in registrations#create:

  Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id
  app/controllers/shopqi/registrations_controller.rb:21:in `create'

**Comment by wyh770406** [comment]
```
  resource.shop.themes.first.theme_id ||= Theme.default.id这一句有问题，估计没有主题的初始化数据
```

**Comment by saberma** [comment]
看起来像是没有默认的主题记录，你有没有运行 `bundle exec rake shopqi:bootstrap`

调试看看

```
$ rails c
> ap Theme.all
> Theme.default.id
```

**Comment by wyh770406** [comment]
ok
