### ISSUE TITLE
webhook 回调这个功能主要用来做什么？能举个例子吗？

### ISSUE THREAD

**Issue by wyh770406** [saberma/shopqi#462]
webhook 回调这个功能主要用来做什么？能举个例子吗？

**Comment by wyh770406** [comment]
现在webhook可以用吗？

**Comment by saberma** [comment]
代码已经写好了，处于测试阶段。没有部署至服务器，还不能使用。

ShopQi 包含了产品、订单和顾客等管理，这些属于电子商务最基本最常用的功能，几乎每个商店都要用到。还有一些商店需要一些特殊的功能，可以通过 Webhook 来扩展。

比如：
你开个游戏点卡网店，要实现顾客成功下单后向顾客邮箱（或手机）发送卡密。
可以用 [shopqi-app-webhook](https://github.com/saberma/shopqi-app-webhook) 建立一个网站 send-card.com 。
ShopQi 会在顾客成功下单时将订单信息发送至 send-card.com，send-card.com 获取这些信息后就可以做相应的操作了。

**Comment by wyh770406** [comment]
ok,thanks
