### ISSUE TITLE
No such file or directory - /home/huxl/projects/shopqi/data/themes/1/current/.

### ISSUE THREAD

**Issue by aabbcc456aa** [saberma/shopqi#472]
按照说明中的部署步骤，执行bundle exec rake "shopqi:bootstrap[mysql]"出现如下错误 
No such file or directory - /home/huxl/projects/shopqi/data/themes/1/current/.，
如果手动创建此文件夹/home/huxl/projects/shopqi/data/themes/2/current/.后 执行 rake db:seed  又出现如下错误/home/huxl/projects/shopqi/data/shops/development/2/themes/2/config/settings_data.json
查看thems表，有一条记录
网上搜了会，没收到类似这样错误及解决方案，所以摆脱了。

**Comment by aabbcc456aa** [comment]
补充下 我是在ubuntu 12.04下测试的，数据库是mysql,代码是前天最新的

**Comment by saberma** [comment]
你试下 `bundle exec rake "shopqi:bootstrap[mysql]" --trace` 看是在哪一行代码报错的

**Comment by aabbcc456aa** [comment]
```
No such file or directory - /home/huxl/projects/shopqi/data/themes/1/current/.
```

/home/huxl/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1515:in `stat'
/home/huxl/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1515:in`block in fu_each_src_dest'
/home/huxl/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1529:in `fu_each_src_dest0'
/home/huxl/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1513:in`fu_each_src_dest'
/home/huxl/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
/home/huxl/projects/shopqi/app/models/shop_theme.rb:204:in`block (2 levels) in class:ShopTheme'
/home/huxl/projects/shopqi/app/models/shop_theme.rb:209:in `create_repo'
/home/huxl/projects/shopqi/app/models/shop_theme.rb:204:in`block in class:ShopTheme'

**Comment by saberma** [comment]
看起来像是 https://github.com/saberma/shopqi/blob/master/app/uploaders/theme_uploader.rb#L54 这个语句没有执行成功。
你在

```
system("tar xjf #{self.path} -C #{current_path}")
```

前面加入两行：

```
p "============================"
p "tar xjf #{self.path} -C #{current_path}"
```

重新执行 `bundle exec rake "shopqi:bootstrap[mysql]" --trace`

控制台会打印出完整的执行语句，你把这个语句在 terminal 直接执行看出现什么错误

**Comment by aabbcc456aa** [comment]
按照你的提示，在 theme_uploader.rb   

```
system("tar xjf #{self.path} -C #{current_path}")  
```

前面加入了输出打印语句  

```
 p "============================"
 p "tar xjf #{self.path} -C #{current_path}"  
```

在控制台没有看到输出语句，估计没执行到这里

**Comment by saberma** [comment]
你加我 gtalk 吧，mahb45@gmail.com

**Comment by aabbcc456aa** [comment]
在saberma 指导下调试很久 首先通过跟踪运行（--trace）知道问题是在创建theme时出错  然后通过console中手动创建theme查看是哪个validates 没有通过，然后把问题又定位到mini_magick上，然后通过手动open目录文件，最终确定就是由mini_magcik无法打开本地图片抛出的错误。
   但是minni_magick打开网络图片却有效，折腾了很久，发现一规律，就是我本地的环境只能打开png,不能打开jpg格式的，此时问题就清晰多了，是ImageMagick安装的依赖包缺少，只安装了png的依赖包（其实可以通过 convert -list configure 命令察看ImageMagick 信息）
其实 https://github.com/saberma/shopqi/wiki/Install 部署说明已经把问题都考虑到了
