### ISSUE TITLE
server启动后访问不了

### ISSUE THREAD

**Issue by aabbcc456aa** [saberma/shopqi#486]
国庆节前，项目已经部署好，可以正常使用。
国庆回来后，bundle exec unicorn_rails -p 4000 -c config/development.unicorn.conf.rb启动后，终端信息正常，但是通过http://www.lvh.me:4000/访问，则出现问题，不能访问了 说找不到这个地址，查看日志，只有连接数据库的log(Connecting to database specified by database.yml)，启动rails c也一切正常

希望能帮助我调试下，看看问题出现在哪里。

**Comment by saberma** [comment]
不好意思，刚查看 issue list 才看到这个 issue。BTW，github 的邮件通知时有时无让人郁闷。

这个问题有可能是你的运营商无法正常访问 lvh.me 导致的，你看能否正常 `ping www.lvh.me`

或者换成通过 http://www.42foo.com:4000 进行访问，访问前请先修改 [`config/app_config.yml`](https://github.com/saberma/shopqi/blob/master/config/app_config.yml#L15) 文件并重启应用服务器

有其他问题请通知我，我会和你一起调试

**Comment by aabbcc456aa** [comment]
按照你的提示，更换了域名配置，然后用新的域名访问，可以打开了，不过还是有问题，就是无法加载css js,查看html.发现js.css.image这些地址没有变，不知道你那边是否还有相应的解决方案。  

另外：我想问下域名和本地服务是怎么样的一个关系，开始我以为域名就是访问本地的一个别名，但是后来我随便换个不行，所以不是我想的这样。

**Comment by saberma** [comment]
js, css 等 asset 域名没有跟配置文件对应，现已更新代码，修正此问题了

你说的没错，域名是访问本地的一个别名，之所以使用 `lvh.me` 或者 `42foo.com`，是为了支持泛域名

https://github.com/saberma/shopqi/commit/8da94af9ed452b2f79f26791ea85a4773a1526e0

**Comment by aabbcc456aa** [comment]
非常感谢！  
更新代码后问题解决了

**Comment by saberma** [comment]
好的，如果还有其他问题或者疑问，可以随时联系我
