### ISSUE TITLE
Error adding the first item

### ISSUE THREAD

**Issue by kirpen** [saberma/shopqi#494]
Hello, here found an error and not know how to fix it.
When you add a new product for the first time, the first product does not assign id 1 and just puts "products /".
All other items are normally "products / 2", "products / 3", "products / 4" ....
Help me find the cause of this error
I can `t find the code that is responsible for assigning the id for a product, it is only in the models:

def url
    "/products/#{self.handle}"
  end

  begin 'shop' #

```
def shop_as_json(options = nil) #
  {
    id: self.id,
    handle: self.handle,
    title: self.title,
    price: self.price,
    url: self.url,
    available: self.available,
    options: self.options.map(&:name),
    variants: self.variants.map(&:shop_as_json),
    featured_image: self.featured_image #
  }
end
```

but where is going to "handle"? I can not find
Help please show only the code where it's going, I'll be able to continue to correct itself.

**Comment by saberma** [comment]
You can debug it from here
https://github.com/saberma/shopqi/blob/master/lib/models/handle.rb#L29

**Comment by kirpen** [comment]
Wow, I did not know that there is a wrap in Chinese Search result links, and that link = product name.
Ok, then it's understandable why I have created this kind of products, "product /", "product / 2", "product / 3" I just used the Russian language in the names of products
Thanks for the help, you can still please tell where you can see the code of the transformation of Chinese into English references, I'll try to write for Russian language validation, if you come work, I will give you, and you lay out for users

**Comment by kirpen** [comment]
Mistake with the first product, has not decided yet to understand why the first product is not intended to "1", and for the next affix "2,3,4,5,6 ..." ie +1
Now I want to solve the problem with validation of the Russian language in the product name.

**Comment by saberma** [comment]
I have just created a product with an Russian name, and there was a problem like you said above.
Here is the reason:

```
Pinyin.t('Китай')
  => "Китай"
Models::Handle.handleize('Китай')
  => ""
```

[These codes](https://github.com/saberma/shopqi/blob/master/lib/models/handle.rb#L11) will make the first product handle to be empty. 

```
while collection.exists?(condition.merge(handle: unique_handle))
  unique_handle = "#{unique_handle}-#{number}"
    number += 1
  end
```

[These codes](https://github.com/saberma/shopqi/blob/master/lib/models/handle.rb#L35) will make the later product's handle to be 2, 3, and 4 etc...

The function of `Pinyin.t` method is transform Chinese to English letters, so I sugget that you'd better find some gem to transform Russian to English letter,and your product's handle will be generated.

https://github.com/flyerhzm/chinese_pinyin

**Comment by kirpen** [comment]
I'm already working on changing chinese_pinyin
Already made ​​the table, in the image file mandarin.dat
And he wrote a letter
https://github.com/janx
asked him to help deal with the processing of a database file with the Unicode character codes mandarin.dat
I'd love to take ready gem
but it is not, I searched everywhere and google is not helping
there is no escape, as always do everything yourself :8ball: ))))))

**Comment by kirpen** [comment]
Hurrah! i will do the binding of the Russian language))
The truth is still not made ​​a choice of both languages ​​like Chinese and Russian.
installation process is simple:

 add to Gemfile:

   gem 'russian', '~> 0.6.0'

```
$ bundle install
```

---

After this, open the file:

  your_app/lib/models/handle.rb

and change the line:

```
Pinyin.t(input).gsub(/[^\w\-\s\.]/, '').strip.downcase.gsub(/\s+|\./, '-')
```

on here this:

```
Russian::Transliteration.transliterate(input).gsub(/[^\w\-\s\.]/, '').strip.downcase.gsub(/\s+|\./, '-')
```

after that you can write the names of products in Russian :)
