### ISSUE TITLE
执行任务时，没有目录

### ISSUE THREAD

**Issue by xiaoyi2013** [saberma/shopqi#495]
当执行 bundle exec rake shopqi:bootstrap时，显示如下信息：
-- assume_migrated_upto_version(20120815032021, ["/home/ding/rails/shopqi/db/migrate"])
rake aborted!
No such file or directory - /home/ding/rails/shopqi/data/themes/1/current/.

Tasks: TOP => db:setup => db:seed => db:seed:development => db:seed:development:shop

请作者看看，是什么问题^_^

**Comment by saberma** [comment]
应该是你本地的 ImageMagick 不支持 PNG 格式的图片处理。

```
identify -list format | grep PNG 
```

参考：https://github.com/saberma/shopqi/issues/472

**Comment by xiaoyi2013** [comment]
您好：
    现在还是执行的时候，碰到了一个新问题：rake aborted!
undefined method `collections' for #Product:0xbe9478c
我用控制台查看了一下，确实没有collections方法：
Loading development environment (Rails 3.2.7)
1.9.3-p392 :001 > Product
 => Product(id: integer, shop_id: integer, handle: string, title: string,
published: boolean, body_html: text, price: float, product_type: string,
vendor: string, created_at: datetime, updated_at: datetime)
1.9.3-p392 :002 > exit

您看看是什么问题

2013/6/1 Saber notifications@github.com

**Comment by saberma** [comment]
得看下详细的日志信息

```
 bundle exec rake shopqi:bootstrap --backtrace
```

**Comment by xiaoyi2013** [comment]
日志的详细信息，我加的参数是 --trace,   --backtrace
下面是我截取的部分相关的日志
-- create_table("weight_based_shipping_rates", {:force=>true})
NOTICE:  CREATE TABLE will create implicit sequence "weight_based_shipping_rates_id_seq" for serial column "weight_based_shipping_rates.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "weight_based_shipping_rates_pkey" for table "weight_based_shipping_rates"
   -> 0.0167s
-- add_index("weight_based_shipping_rates", ["shipping_id"], {:name=>"index_weight_based_shipping_rates_on_shipping_id"})
   -> 0.0103s
-- initialize_schema_migrations_table()
   -> 0.0010s
-- assume_migrated_upto_version(20120815032021, ["/home/ding/rails/shopqi/db/migrate"])
   -> 0.0026s
*\* Invoke db:structure:load_if_sql (first_time)
*\* Invoke db:create 
*\* Execute db:structure:load_if_sql
*\* Invoke db:seed (first_time)
*\* Invoke db:seed:common (first_time)
*\* Invoke db:seed:original (first_time)
*\* Execute db:seed:original
*\* Invoke db:abort_if_pending_migrations (first_time)
*\* Invoke environment 
*\* Invoke db:load_config 
*\* Execute db:abort_if_pending_migrations
*\* Execute db:seed:common
*\* Invoke db:seed:development (first_time)
*\* Invoke db:seed:common 
*\* Invoke db:seed:development:shop (first_time)
*\* Invoke db:abort_if_pending_migrations 
*\* Execute db:seed:development:shop
rake aborted!
undefined method `collections' for #<Product:0xc085104>
/usr/local/rvm/gems/ruby-1.9.3-p392@rails3/gems/activemodel-3.2.7/lib/active_model/attribute_methods.rb:407:in`method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p392@rails3/gems/activerecord-3.2.7/lib/active_record/attribute_methods.rb:149:in `method_missing'
db/seeds/development/shop.seeds.rb:48:in`block in <top (required)>'
db/seeds/development/shop.seeds.rb:46:in `upto'
db/seeds/development/shop.seeds.rb:46:in`<top (required)>'

**Comment by saberma** [comment]
错误日志中显示 `db/seeds/development/shop.seeds.rb` 第 `48` 行抛出异常：缺少 `collections` 方法，但是这个文件的第 `48` 行调用的是 `product.custom_collections` 方法，你本地有做修改吗？

```
1.upto(6) do |i|
  product = myshopqi.products.create title: "示例商品#{i}", handle: "example-#{i}", body_html: product_description, product_type: '手机', vendor: 'ShopQi'
  product.custom_collections << frontpage_collection
  product.save
end
```

或者你先把第 `48` 行注释掉看看

**Comment by xiaoyi2013** [comment]
现在的程序源码中是 product.collections << frontpage_collection，改为：
product.custom_collections << frontpage_collection， 后，顺利执行，请作者看下master里面的源码
我先跑下程序，看看我实在没问题了，再close吧，^_^

**Comment by saberma** [comment]
你弄错了吧，现在的文件源码在 [这里](https://github.com/saberma/shopqi/blob/master/db/seeds/development/shop.seeds.rb#L48)。

好的，没问题了再 `close`

**Comment by xiaoyi2013** [comment]
恩，我找的源码是别人克隆你的，重新部署，没有问题，启用的域名是42foo.com
多谢作者解答！
