### ISSUE TITLE
rake db:seed 报错 undefined method `Factory' for #<Seedbank::Runner:

### ISSUE THREAD

**Issue by i3zhe** [saberma/shopqi#498]
`rake aborted!
undefined method`Factory' for #Seedbank::Runner:0x007f8c6be6d2d8
/Users/user/Sites/shopqi/db/seeds/development/shop.seeds.rb:9:in `block in define_seed_task'
/Users/user/.rvm/gems/ruby-1.9.3-p392@rails3/bundler/gems/seedbank-c7a272751336/lib/seedbank/dsl.rb:24:in`module_eval'
/Users/user/.rvm/gems/ruby-1.9.3-p392@rails3/bundler/gems/seedbank-c7a272751336/lib/seedbank/dsl.rb:24:in `block in define_seed_task'
/Users/user/Sites/shopqi/lib/tasks/bootstrap.rake:35:in`block (2 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-1.9.3-p392@rails3/bin/ruby_noexec_wrapper:14:in `eval'
/Users/user/.rvm/gems/ruby-1.9.3-p392@rails3/bin/ruby_noexec_wrapper:14:in`<main>'
Tasks: TOP => db:setup => db:seed => db:seed:development => db:seed:development:shop`

**Comment by saberma** [comment]
看到你在 https://github.com/saberma/shopqi/issues/497 已经解决这个问题了。
