### ISSUE TITLE
cdn asset_path 怎麼修改?

### ISSUE THREAD

**Issue by clammy77** [saberma/shopqi#499]
你好，我想要修改所有 images 的 asset_path。我已經再 development.rb 裡面修改了，不過所有assets 還是想要從 cdn....去找。

感謝。

**Comment by saberma** [comment]
你可以试下修改
https://github.com/saberma/shopqi/blob/master/config/environments/development.rb#L27

```
 config.action_controller.asset_host = Proc.new { |source|
    "//cdn.#{Setting.domain.host}#{Setting.domain.port}"
  }
```
