### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by web1989** [saberma/shopqi#503]
I have problem to install,can anyone help me please.

thanks

**Comment by web1989** [comment]
any people?

**Comment by BeshoyAtef** [comment]
Can you please specify the problem and attach more info ?

**Comment by web1989** [comment]
I never installed before any other platform in Ruby on Rails.
in my VPS I installed
Ruby
Rails 3.2 
Redis 
MySql

but now I can not install the platform with this code  .
I unzip files for my folder  shop/public and tried to run the commands

Installation[use MySQL]

$ script/development/use_mysql
$ bundle
$ bundle exec rake "shopqi:bootstrap[mysql]"
Usage

Start the server

$ bundle exec unicorn_rails -p 4000 -c config/development.unicorn.conf.rb

I'm certainly doing something wrong but I do not know where

**Comment by BeshoyAtef** [comment]
@claudineireal  can you please send me a screenshot of the terminal

**Comment by web1989** [comment]
@BeshoSmile a issue, I have to create a project for this installation?
sample
$ rails new shop
$ cd shop
$ rails server
and unzip files ShopQi in this folder "shop" for make installation?
