### ISSUE TITLE
用户可以设置支付信息

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#51]
暂时只需支持支付宝接口
包括额外设置、政策（先能保存进去，待网店前台开发了再补显示效果）

开始开发时跟我要接口信息

**Comment by liwh** [comment]
已完成后台管理功能

**Comment by saberma** [comment]
- 支付宝校验不通过时不应该隐藏输入form
- 普通支付新增记录后，编辑操作的使用频率比删除的高很多，还是要放在支付名称的后面
